// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

console.log("Hello, my friend!");

function greeting(person) {
  if (typeof person === "number") {
    if (person !== 0) {
      return "Hello Director.";
    } else {
      return "Hey Professor!";
    }
  } else {
    var anyOtherName = person[0];
    if (anyOtherName === "Richard") {
      return "Still here Ricky?";
    } else {
      return "Hey, " + (anyOtherName + ".");
    }
  }
}

function f(param) {
  if (param !== undefined) {
    return "Hey";
  } else {
    return "None";
  }
}

exports.greeting = greeting;
exports.f = f;
/*  Not a pure module */
