[package]
name = "raven_mpsc"
version = "0.1.0"
authors = ["Julian Pokrovsky <juliankul@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
