test:
	javac -cp .:./algs4.jar Test.java && java -cp .:./algs4.jar Test

w1:
	javac -cp .:./algs4.jar week1/Main.java && java -cp .:./algs4.jar week1/Main

w1h:
	javac -cp .:./algs4.jar week1/Homework.java && java -cp .:./algs4.jar week1/Homework
