test:
	javac -cp .:./algs4.jar Test.java && java -cp .:./algs4.jar Test

w1:
	javac -cp .:./algs4.jar week1/Main.java && java -cp .:./algs4.jar week1/Main

w1h:
	javac -cp .:./algs4.jar week1/Homework.java && java -cp .:./algs4.jar week1/Homework

w1ip:
	javac -cp .:./algs4.jar week1/percolation/InteractivePercolationVisualizer.java && java -cp .:./algs4.jar week1/percolation/InteractivePercolationVisualizer

w1p:
	javac -cp .:./algs4.jar week1/percolation/PercolationVisualizer.java && java -cp .:./algs4.jar week1/percolation/PercolationVisualizer ./week1/percolation/eagle25.txt
